on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build
      - run: sam build -t dev-template.yaml -b build/dev-template.yaml

      - name: Deploy
      - run: sam deploy \
            --template build/dev-template.yaml
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name ${{ secrets.STACK_NAME_DEV }} \
            --capabilities CAPABILITY_IAM \
            --image-repositories Lambda1={{ secrets.LAMBDA1_ECR_DEV }}
            --image-repositories Lambda2={{ secrets.LAMBDA2_ECR_DEV }}